GET http://localhost:3000/blocks


###

POST http://localhost:3000/blocks
Content-Type: application/json

{
    "data": "Second block!"
}

###
POST http://localhost:3000/peers
Content-Type: application/json

{
    "peer": "ws://localhost:4000"
}